#!/bin/bash

if [[ -e venv ]]; then
    rm -rf venv
fi

virtualenv -p python3 venv

pushd venv; . bin/activate; popd

echo "//"
echo "// install pygame"
echo "//"
# local fork I use to save from downloading again
pip install /home/cturner/opt/20161029.memlab.cturner.aa.pygame.clone/pygame
#pip install hg+http://bitbucket.org/pygame/pygame

echo "//"
echo "// install src as source directory"
echo "//"
pushd src
pip install -e .
rm -rf solent.client.egg-info
popd

echo "//"
echo "// finishing"
echo "//"
echo
echo "now do this:"
echo "  pushd venv; . bin/activate; popd"
echo "  python -m solent.client.games.sandbox"
echo

