#!/bin/bash

pushd ../venv
. bin/activate
popd

pip install -e .

#python -m solent.client.games.sandbox --win
#python -m solent.client.games.sandbox --tty

python -m solent.client.games.demo_experience --win
#python -m solent.client.games.demo_experience --tty

rm -rf solent.client.egg-info

