#!/bin/bash
#
# This script 
#

pushd ../venv
. bin/activate
popd

#python -m solent.client.games.sandbox --win
#python -m solent.client.games.sandbox --tty
#python -m solent.client.games.demo_experience --win
python -m solent.client.games.demo_experience --tty

